window.designQaData = {
  projects: [
    {
      name: "Design QA Board MVP",
      owner: "지영",
      status: "검토중",
      progress: 42,
      screens: 12,
      memo: "초급자용 UIUX 프로세스 이해를 돕는 MVP 제작 과정의 대표 결과물입니다.",
    },
    {
      name: "Portfolio Routine App",
      owner: "민아",
      status: "대기",
      progress: 18,
      screens: 8,
      memo: "루틴 실행 화면과 회고 플로우를 검토 중입니다.",
    },
    {
      name: "Research Insight Board",
      owner: "현우",
      status: "완료",
      progress: 88,
      screens: 10,
      memo: "태그 필터와 인사이트 묶기 플로우 QA가 끝났습니다.",
    },
  ],
  screens: [
    { name: "홈 대시보드", checklist: 8, status: "warning" },
    { name: "프로젝트 목록", checklist: 6, status: "success" },
    { name: "프로젝트 상세", checklist: 9, status: "info" },
    { name: "화면 QA 상세", checklist: 12, status: "danger" },
    { name: "QA 리포트", checklist: 5, status: "info" },
  ],
  issues: [
    {
      id: 1,
      title: "모바일에서 필터 칩 간격이 너무 좁음",
      screen: "이슈 보드",
      owner: "지영",
      status: "todo",
      priority: "high",
    },
    {
      id: 2,
      title: "업로드 에러 문구에 재시도 안내가 부족함",
      screen: "화면 QA 상세",
      owner: "민아",
      status: "doing",
      priority: "high",
    },
    {
      id: 3,
      title: "리포트 테이블 컬럼의 반응형 우선순위 필요",
      screen: "QA 리포트",
      owner: "지영",
      status: "todo",
      priority: "medium",
    },
    {
      id: 4,
      title: "성공 토스트가 하단 CTA와 겹침",
      screen: "화면 QA 상세",
      owner: "현우",
      status: "done",
      priority: "low",
    },
    {
      id: 5,
      title: "대시보드 카드 라벨 대비가 약함",
      screen: "대시보드",
      owner: "민아",
      status: "doing",
      priority: "medium",
    },
  ],
  checklistItems: [
    "390px 모바일에서 주요 CTA가 스크롤 없이 보인다.",
    "상태 뱃지는 색상과 텍스트를 함께 사용한다.",
    "빈 상태, 로딩, 에러, 성공 상태가 모두 표현되어 있다.",
    "일반 콘텐츠는 1440px 컨테이너 안에 정렬된다.",
    "이슈 보드는 1680px 작업형 컨테이너까지 확장된다.",
    "모든 컨트롤의 focus-visible 상태가 명확하다.",
  ],
  reportRows: [
    ["홈 대시보드", 3, 1, "검토중", "모바일에서 필터 간격 최종 QA가 필요합니다."],
    ["화면 QA 상세", 4, 2, "막힘", "업로드 에러 상태의 재시도 문구를 더 명확히 해야 합니다."],
    ["QA 리포트", 1, 0, "공유 준비", "멘토 리뷰용으로 공유할 수 있습니다."],
  ],
};
